// Auto-generated by generate_data.cpp
const demoFS = {
  "name": "root",
  "type": "folder",
  "children": [
    {
      "name": ".git",
      "type": "folder",
      "children": [
        {
          "name": "hooks",
          "type": "folder",
          "children": [
            {
              "name": "applypatch-msg.sample",
              "type": "file",
              "size": 478,
              "modified": 1754748752537
            },
            {
              "name": "commit-msg.sample",
              "type": "file",
              "size": 896,
              "modified": 1754748752533
            },
            {
              "name": "fsmonitor-watchman.sample",
              "type": "file",
              "size": 4726,
              "modified": 1754748752536
            },
            {
              "name": "post-update.sample",
              "type": "file",
              "size": 189,
              "modified": 1754748752537
            },
            {
              "name": "pre-applypatch.sample",
              "type": "file",
              "size": 424,
              "modified": 1754748752534
            },
            {
              "name": "pre-commit.sample",
              "type": "file",
              "size": 1649,
              "modified": 1754748752532
            },
            {
              "name": "pre-merge-commit.sample",
              "type": "file",
              "size": 416,
              "modified": 1754748752532
            },
            {
              "name": "pre-push.sample",
              "type": "file",
              "size": 1374,
              "modified": 1754748752532
            },
            {
              "name": "pre-rebase.sample",
              "type": "file",
              "size": 4898,
              "modified": 1754748752535
            },
            {
              "name": "pre-receive.sample",
              "type": "file",
              "size": 544,
              "modified": 1754748752536
            },
            {
              "name": "prepare-commit-msg.sample",
              "type": "file",
              "size": 1492,
              "modified": 1754748752534
            },
            {
              "name": "push-to-checkout.sample",
              "type": "file",
              "size": 2783,
              "modified": 1754748752535
            },
            {
              "name": "sendemail-validate.sample",
              "type": "file",
              "size": 2308,
              "modified": 1754748752535
            },
            {
              "name": "update.sample",
              "type": "file",
              "size": 3650,
              "modified": 1754748752536
            }
          ]
        },
        {
          "name": "info",
          "type": "folder",
          "children": [
            {
              "name": "exclude",
              "type": "file",
              "size": 240,
              "modified": 1754748752527
            }
          ]
        },
        {
          "name": "logs",
          "type": "folder",
          "children": [
            {
              "name": "refs",
              "type": "folder",
              "children": [
                {
                  "name": "heads",
                  "type": "folder",
                  "children": [
                    {
                      "name": "main",
                      "type": "file",
                      "size": 466,
                      "modified": 1754751094350
                    }
                  ]
                },
                {
                  "name": "remotes",
                  "type": "folder",
                  "children": [
                    {
                      "name": "origin",
                      "type": "folder",
                      "children": [
                        {
                          "name": "HEAD",
                          "type": "file",
                          "size": 148,
                          "modified": 1754749216548
                        },
                        {
                          "name": "main",
                          "type": "file",
                          "size": 471,
                          "modified": 1754751122899
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "HEAD",
              "type": "file",
              "size": 466,
              "modified": 1754751094350
            }
          ]
        },
        {
          "name": "objects",
          "type": "folder",
          "children": [
            {
              "name": "05",
              "type": "folder",
              "children": [
                {
                  "name": "c1ca8c1fe77d8f7bd26f0b0ae406cd774317ce",
                  "type": "file",
                  "size": 2554,
                  "modified": 1754749174995
                }
              ]
            },
            {
              "name": "08",
              "type": "folder",
              "children": [
                {
                  "name": "fc3583f4438d1ca84c3b7555538948d7d2e03c",
                  "type": "file",
                  "size": 3576,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "14",
              "type": "folder",
              "children": [
                {
                  "name": "08280aeb0c38a7b6927d7d5a9293a5463d74b7",
                  "type": "file",
                  "size": 78,
                  "modified": 1754749178062
                }
              ]
            },
            {
              "name": "17",
              "type": "folder",
              "children": [
                {
                  "name": "ac856bdf5e3bf1bd8b82d20d9fb6bd58ed2bcc",
                  "type": "file",
                  "size": 105,
                  "modified": 1754749178062
                }
              ]
            },
            {
              "name": "18",
              "type": "folder",
              "children": [
                {
                  "name": "da6603a729a4a9e993ac0912148a1a90fa4c07",
                  "type": "file",
                  "size": 245,
                  "modified": 1754749174995
                }
              ]
            },
            {
              "name": "1f",
              "type": "folder",
              "children": [
                {
                  "name": "ea04a858cd0755d58b1bbc3bdfb069826a1d86",
                  "type": "file",
                  "size": 66,
                  "modified": 1754751094346
                }
              ]
            },
            {
              "name": "28",
              "type": "folder",
              "children": [
                {
                  "name": "cfea3da39077ea37771c1021b0b1fca7264bda",
                  "type": "file",
                  "size": 60,
                  "modified": 1754749178061
                }
              ]
            },
            {
              "name": "2a",
              "type": "folder",
              "children": [
                {
                  "name": "b67e8ca028c3d23b91343f4f78659170ffd7f7",
                  "type": "file",
                  "size": 158,
                  "modified": 1754750889971
                }
              ]
            },
            {
              "name": "35",
              "type": "folder",
              "children": [
                {
                  "name": "5856856242204dc2656564406374589a4995da",
                  "type": "file",
                  "size": 105,
                  "modified": 1754751094346
                }
              ]
            },
            {
              "name": "3b",
              "type": "folder",
              "children": [
                {
                  "name": "cfd42cdfa82031c006c775f9f0a04167baf22a",
                  "type": "file",
                  "size": 60,
                  "modified": 1754751094346
                }
              ]
            },
            {
              "name": "3c",
              "type": "folder",
              "children": [
                {
                  "name": "3898696b6c23571f7ffceff49047e32d4a9234",
                  "type": "file",
                  "size": 190,
                  "modified": 1754751094347
                }
              ]
            },
            {
              "name": "43",
              "type": "folder",
              "children": [
                {
                  "name": "734a04730ec497a5760cdf7c1cabc621396eac",
                  "type": "file",
                  "size": 304,
                  "modified": 1754749174994
                }
              ]
            },
            {
              "name": "45",
              "type": "folder",
              "children": [
                {
                  "name": "026ae8930024a74109eae1a5260423720ae6a0",
                  "type": "file",
                  "size": 55,
                  "modified": 1754749178062
                }
              ]
            },
            {
              "name": "48",
              "type": "folder",
              "children": [
                {
                  "name": "5b330033bfceb31cde773e169dedd567a16d5b",
                  "type": "file",
                  "size": 300,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "4b",
              "type": "folder",
              "children": [
                {
                  "name": "1b0501579b4a7cc3bd419282746cc8a1e3bd8e",
                  "type": "file",
                  "size": 86,
                  "modified": 1754749178061
                }
              ]
            },
            {
              "name": "4e",
              "type": "folder",
              "children": [
                {
                  "name": "43f0132149ed7de7930a16ed406bdcf8fbe3dc",
                  "type": "file",
                  "size": 3576,
                  "modified": 1754750884813
                }
              ]
            },
            {
              "name": "53",
              "type": "folder",
              "children": [
                {
                  "name": "4cffbe30c1ab71162ff0eaf43e35120e3948a4",
                  "type": "file",
                  "size": 105,
                  "modified": 1754750889969
                }
              ]
            },
            {
              "name": "58",
              "type": "folder",
              "children": [
                {
                  "name": "981909759660f6d2677bf18107388ff0639972",
                  "type": "file",
                  "size": 77,
                  "modified": 1754749174995
                }
              ]
            },
            {
              "name": "62",
              "type": "folder",
              "children": [
                {
                  "name": "ac8461444d1b8cce739104be8ca79e8dd6f6e5",
                  "type": "file",
                  "size": 82,
                  "modified": 1754749178062
                }
              ]
            },
            {
              "name": "69",
              "type": "folder",
              "children": [
                {
                  "name": "c6527a488ab59d4ba266dea1ad9d54df290a8b",
                  "type": "file",
                  "size": 141,
                  "modified": 1754751094346
                }
              ]
            },
            {
              "name": "71",
              "type": "folder",
              "children": [
                {
                  "name": "2c730943565f9031f0a932f09610945bdb9ca9",
                  "type": "file",
                  "size": 411,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "74",
              "type": "folder",
              "children": [
                {
                  "name": "b68022823a8507bb8a6a5ec9c5f0f5f3a139c3",
                  "type": "file",
                  "size": 189,
                  "modified": 1754750889969
                }
              ]
            },
            {
              "name": "75",
              "type": "folder",
              "children": [
                {
                  "name": "960da906af844351891ca45cf38c4961693639",
                  "type": "file",
                  "size": 388,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "78",
              "type": "folder",
              "children": [
                {
                  "name": "d5c6ee86c10523133f07bf05fccf10c7a751be",
                  "type": "file",
                  "size": 129,
                  "modified": 1754749178064
                }
              ]
            },
            {
              "name": "7f",
              "type": "folder",
              "children": [
                {
                  "name": "87d66d6e8a45ff31530fd48c026def46e96a7f",
                  "type": "file",
                  "size": 82,
                  "modified": 1754750889969
                }
              ]
            },
            {
              "name": "81",
              "type": "folder",
              "children": [
                {
                  "name": "ae5349027d26be285e7ef789ff0ae2a606b577",
                  "type": "file",
                  "size": 106,
                  "modified": 1754749178061
                }
              ]
            },
            {
              "name": "93",
              "type": "folder",
              "children": [
                {
                  "name": "1a3b7fcdbab516dbbc3d0171eb7016b6b0e6d3",
                  "type": "file",
                  "size": 155,
                  "modified": 1754749174996
                }
              ]
            },
            {
              "name": "96",
              "type": "folder",
              "children": [
                {
                  "name": "75c98f17e677b775ec9021477f1f425cb5fd68",
                  "type": "file",
                  "size": 121,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "97",
              "type": "folder",
              "children": [
                {
                  "name": "09c9397df2d4612eef1b0481a2c622f3bddd3d",
                  "type": "file",
                  "size": 361,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "98",
              "type": "folder",
              "children": [
                {
                  "name": "13bcfbbb145a51107a377c0c0f3f2405845c4b",
                  "type": "file",
                  "size": 104,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "a0",
              "type": "folder",
              "children": [
                {
                  "name": "9fe178800e5ad2e7b72e2007de95fe8cb82410",
                  "type": "file",
                  "size": 61,
                  "modified": 1754749178062
                }
              ]
            },
            {
              "name": "a4",
              "type": "folder",
              "children": [
                {
                  "name": "2ac13fa220efc6c9f8f34144a120d838121695",
                  "type": "file",
                  "size": 221,
                  "modified": 1754751090734
                }
              ]
            },
            {
              "name": "a8",
              "type": "folder",
              "children": [
                {
                  "name": "725147bbe66332a9fe98c3f26221e8cd9912a5",
                  "type": "file",
                  "size": 160,
                  "modified": 1754749174995
                },
                {
                  "name": "a6bda78407be3d05d290ea015c1b51d27188c0",
                  "type": "file",
                  "size": 24,
                  "modified": 1754749174994
                }
              ]
            },
            {
              "name": "ac",
              "type": "folder",
              "children": [
                {
                  "name": "a6b0312514d6bbf7050ea02e20c7f6087f7209",
                  "type": "file",
                  "size": 159,
                  "modified": 1754751094349
                }
              ]
            },
            {
              "name": "c2",
              "type": "folder",
              "children": [
                {
                  "name": "aeb1a28fee85c6057b2db651531fa1cb2249e5",
                  "type": "file",
                  "size": 107,
                  "modified": 1754749174994
                }
              ]
            },
            {
              "name": "ce",
              "type": "folder",
              "children": [
                {
                  "name": "39a9497d17fad0659ed6a2b2263a6b1787630a",
                  "type": "file",
                  "size": 83,
                  "modified": 1754751094346
                }
              ]
            },
            {
              "name": "cf",
              "type": "folder",
              "children": [
                {
                  "name": "8466e5b82c7e04cc2af0415aec3931f195f2eb",
                  "type": "file",
                  "size": 243,
                  "modified": 1754749174996
                }
              ]
            },
            {
              "name": "d0",
              "type": "folder",
              "children": [
                {
                  "name": "2a25bb9eae103a1ae7da51936ee495579ba335",
                  "type": "file",
                  "size": 66,
                  "modified": 1754749178061
                }
              ]
            },
            {
              "name": "d5",
              "type": "folder",
              "children": [
                {
                  "name": "40af72fed2bca2ca63913e3819400b2101bd29",
                  "type": "file",
                  "size": 189,
                  "modified": 1754749178062
                }
              ]
            },
            {
              "name": "info",
              "type": "folder",
              "children": [
              ]
            },
            {
              "name": "pack",
              "type": "folder",
              "children": [
              ]
            }
          ]
        },
        {
          "name": "refs",
          "type": "folder",
          "children": [
            {
              "name": "heads",
              "type": "folder",
              "children": [
                {
                  "name": "main",
                  "type": "file",
                  "size": 41,
                  "modified": 1754751094350
                }
              ]
            },
            {
              "name": "remotes",
              "type": "folder",
              "children": [
                {
                  "name": "origin",
                  "type": "folder",
                  "children": [
                    {
                      "name": "HEAD",
                      "type": "file",
                      "size": 30,
                      "modified": 1754749216548
                    },
                    {
                      "name": "main",
                      "type": "file",
                      "size": 41,
                      "modified": 1754751122899
                    }
                  ]
                }
              ]
            },
            {
              "name": "tags",
              "type": "folder",
              "children": [
              ]
            }
          ]
        },
        {
          "name": "COMMIT_EDITMSG",
          "type": "file",
          "size": 2,
          "modified": 1754751094349
        },
        {
          "name": "config",
          "type": "file",
          "size": 266,
          "modified": 1754749183885
        },
        {
          "name": "description",
          "type": "file",
          "size": 73,
          "modified": 1754748752528
        },
        {
          "name": "FETCH_HEAD",
          "type": "file",
          "size": 97,
          "modified": 1754752413361
        },
        {
          "name": "HEAD",
          "type": "file",
          "size": 21,
          "modified": 1754748755542
        },
        {
          "name": "index",
          "type": "file",
          "size": 1699,
          "modified": 1754751094347
        },
        {
          "name": "ORIG_HEAD",
          "type": "file",
          "size": 41,
          "modified": 1754751120543
        }
      ]
    },
    {
      "name": "public",
      "type": "folder",
      "children": [
        {
          "name": "C++",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
                {
                  "name": "de_i18n.yaml",
                  "type": "file",
                  "size": 107,
                  "modified": 1754750855700
                },
                {
                  "name": "jp_i18n.yaml",
                  "type": "file",
                  "size": 122,
                  "modified": 1754750855700
                }
              ]
            },
            {
              "name": "CPP_de.html",
              "type": "file",
              "size": 862,
              "modified": 1754750855911,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/C++/CPP_de.html"
            },
            {
              "name": "CPP_en.html",
              "type": "file",
              "size": 844,
              "modified": 1754750855771,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/C++/CPP_en.html"
            },
            {
              "name": "CPP_jp.html",
              "type": "file",
              "size": 892,
              "modified": 1754750855842,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/C++/CPP_jp.html"
            }
          ]
        },
        {
          "name": "Linux",
          "type": "folder",
          "children": [
            {
              "name": "Linux_install_en.html",
              "type": "file",
              "size": 382,
              "modified": 1754750855700,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/Linux/Linux_install_en.html"
            }
          ]
        },
        {
          "name": "Netlify",
          "type": "folder",
          "children": [
            {
              "name": "Netlify_en.html",
              "type": "file",
              "size": 467,
              "modified": 1754750855940,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/Netlify/Netlify_en.html"
            }
          ]
        }
      ]
    },
    {
      "name": "src",
      "type": "folder",
      "children": [
        {
          "name": "C++",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
                {
                  "name": "de_i18n.yaml",
                  "type": "file",
                  "size": 107,
                  "modified": 1754744695563
                },
                {
                  "name": "jp_i18n.yaml",
                  "type": "file",
                  "size": 122,
                  "modified": 1754744705563
                }
              ]
            },
            {
              "name": "CPP.md",
              "type": "file",
              "size": 249,
              "modified": 1754744781382
            }
          ]
        },
        {
          "name": "Linux",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
              ]
            },
            {
              "name": "Linux_install.md",
              "type": "file",
              "size": 208,
              "modified": 1754748932087
            }
          ]
        },
        {
          "name": "Netlify",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
              ]
            },
            {
              "name": "Netlify.md",
              "type": "file",
              "size": 353,
              "modified": 1754748660946
            }
          ]
        }
      ]
    },
    {
      "name": ".gitignore",
      "type": "file",
      "size": 9,
      "modified": 1754748853512
    },
    {
      "name": "create_index",
      "type": "file",
      "size": 116440,
      "modified": 1754752538276
    },
    {
      "name": "create_index.cpp",
      "type": "file",
      "size": 5741,
      "modified": 1754752209394
    },
    {
      "name": "data.js",
      "type": "file",
      "size": 0,
      "modified": 1754752574784
    },
    {
      "name": "generator",
      "type": "file",
      "size": 632592,
      "modified": 1754750854374
    },
    {
      "name": "generator.cpp",
      "type": "file",
      "size": 12192,
      "modified": 1754751085703
    },
    {
      "name": "index.html",
      "type": "file",
      "size": 2691,
      "modified": 1754752332674,
      "url": "https://fascinating-babka-9cd698.netlify.app/index.html"
    },
    {
      "name": "index_template.html",
      "type": "file",
      "size": 8949,
      "modified": 1754751881819,
      "url": "https://fascinating-babka-9cd698.netlify.app/index_template.html"
    },
    {
      "name": "prompt.chatgpt",
      "type": "file",
      "size": 362,
      "modified": 1754744397674
    }
  ]
};
