// Auto-generated by generate_data.cpp
const demoFS = {
  "name": "root",
  "type": "folder",
  "children": [
    {
      "name": ".git",
      "type": "folder",
      "children": [
        {
          "name": "hooks",
          "type": "folder",
          "children": [
            {
              "name": "applypatch-msg.sample",
              "type": "file",
              "size": 478,
              "modified": 1754748752537,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/applypatch-msg.sample"
            },
            {
              "name": "commit-msg.sample",
              "type": "file",
              "size": 896,
              "modified": 1754748752533,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/commit-msg.sample"
            },
            {
              "name": "fsmonitor-watchman.sample",
              "type": "file",
              "size": 4726,
              "modified": 1754748752536,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/fsmonitor-watchman.sample"
            },
            {
              "name": "post-update.sample",
              "type": "file",
              "size": 189,
              "modified": 1754748752537,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/post-update.sample"
            },
            {
              "name": "pre-applypatch.sample",
              "type": "file",
              "size": 424,
              "modified": 1754748752534,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/pre-applypatch.sample"
            },
            {
              "name": "pre-commit.sample",
              "type": "file",
              "size": 1649,
              "modified": 1754748752532,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/pre-commit.sample"
            },
            {
              "name": "pre-merge-commit.sample",
              "type": "file",
              "size": 416,
              "modified": 1754748752532,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/pre-merge-commit.sample"
            },
            {
              "name": "pre-push.sample",
              "type": "file",
              "size": 1374,
              "modified": 1754748752532,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/pre-push.sample"
            },
            {
              "name": "pre-rebase.sample",
              "type": "file",
              "size": 4898,
              "modified": 1754748752535,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/pre-rebase.sample"
            },
            {
              "name": "pre-receive.sample",
              "type": "file",
              "size": 544,
              "modified": 1754748752536,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/pre-receive.sample"
            },
            {
              "name": "prepare-commit-msg.sample",
              "type": "file",
              "size": 1492,
              "modified": 1754748752534,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/prepare-commit-msg.sample"
            },
            {
              "name": "push-to-checkout.sample",
              "type": "file",
              "size": 2783,
              "modified": 1754748752535,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/push-to-checkout.sample"
            },
            {
              "name": "sendemail-validate.sample",
              "type": "file",
              "size": 2308,
              "modified": 1754748752535,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/sendemail-validate.sample"
            },
            {
              "name": "update.sample",
              "type": "file",
              "size": 3650,
              "modified": 1754748752536,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/hooks/update.sample"
            }
          ]
        },
        {
          "name": "info",
          "type": "folder",
          "children": [
            {
              "name": "exclude",
              "type": "file",
              "size": 240,
              "modified": 1754748752527,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/info/exclude"
            }
          ]
        },
        {
          "name": "logs",
          "type": "folder",
          "children": [
            {
              "name": "refs",
              "type": "folder",
              "children": [
                {
                  "name": "heads",
                  "type": "folder",
                  "children": [
                    {
                      "name": "main",
                      "type": "file",
                      "size": 618,
                      "modified": 1754753588410,
                      "url": "https://fascinating-babka-9cd698.netlify.app/.git/logs/refs/heads/main"
                    }
                  ]
                },
                {
                  "name": "remotes",
                  "type": "folder",
                  "children": [
                    {
                      "name": "origin",
                      "type": "folder",
                      "children": [
                        {
                          "name": "HEAD",
                          "type": "file",
                          "size": 148,
                          "modified": 1754749216548,
                          "url": "https://fascinating-babka-9cd698.netlify.app/.git/logs/refs/remotes/origin/HEAD"
                        },
                        {
                          "name": "main",
                          "type": "file",
                          "size": 628,
                          "modified": 1754753594163,
                          "url": "https://fascinating-babka-9cd698.netlify.app/.git/logs/refs/remotes/origin/main"
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "HEAD",
              "type": "file",
              "size": 618,
              "modified": 1754753588410,
              "url": "https://fascinating-babka-9cd698.netlify.app/.git/logs/HEAD"
            }
          ]
        },
        {
          "name": "objects",
          "type": "folder",
          "children": [
            {
              "name": "03",
              "type": "folder",
              "children": [
                {
                  "name": "0cf33ad344d504d2b86e3e357df8b552cd160b",
                  "type": "file",
                  "size": 2324,
                  "modified": 1754753585288,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/03/0cf33ad344d504d2b86e3e357df8b552cd160b"
                }
              ]
            },
            {
              "name": "05",
              "type": "folder",
              "children": [
                {
                  "name": "c1ca8c1fe77d8f7bd26f0b0ae406cd774317ce",
                  "type": "file",
                  "size": 2554,
                  "modified": 1754749174995,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/05/c1ca8c1fe77d8f7bd26f0b0ae406cd774317ce"
                }
              ]
            },
            {
              "name": "08",
              "type": "folder",
              "children": [
                {
                  "name": "fc3583f4438d1ca84c3b7555538948d7d2e03c",
                  "type": "file",
                  "size": 3576,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/08/fc3583f4438d1ca84c3b7555538948d7d2e03c"
                }
              ]
            },
            {
              "name": "14",
              "type": "folder",
              "children": [
                {
                  "name": "08280aeb0c38a7b6927d7d5a9293a5463d74b7",
                  "type": "file",
                  "size": 78,
                  "modified": 1754749178062,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/14/08280aeb0c38a7b6927d7d5a9293a5463d74b7"
                }
              ]
            },
            {
              "name": "17",
              "type": "folder",
              "children": [
                {
                  "name": "ac856bdf5e3bf1bd8b82d20d9fb6bd58ed2bcc",
                  "type": "file",
                  "size": 105,
                  "modified": 1754749178062,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/17/ac856bdf5e3bf1bd8b82d20d9fb6bd58ed2bcc"
                }
              ]
            },
            {
              "name": "18",
              "type": "folder",
              "children": [
                {
                  "name": "da6603a729a4a9e993ac0912148a1a90fa4c07",
                  "type": "file",
                  "size": 245,
                  "modified": 1754749174995,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/18/da6603a729a4a9e993ac0912148a1a90fa4c07"
                }
              ]
            },
            {
              "name": "1e",
              "type": "folder",
              "children": [
                {
                  "name": "4de7f4c8c4e0a881016b21bcab57b71d843cd3",
                  "type": "file",
                  "size": 3750,
                  "modified": 1754753585288,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/1e/4de7f4c8c4e0a881016b21bcab57b71d843cd3"
                }
              ]
            },
            {
              "name": "1f",
              "type": "folder",
              "children": [
                {
                  "name": "ea04a858cd0755d58b1bbc3bdfb069826a1d86",
                  "type": "file",
                  "size": 66,
                  "modified": 1754751094346,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/1f/ea04a858cd0755d58b1bbc3bdfb069826a1d86"
                }
              ]
            },
            {
              "name": "22",
              "type": "folder",
              "children": [
                {
                  "name": "d28d55ebfb3e13bd54ecef84eff22594fa4e34",
                  "type": "file",
                  "size": 36384,
                  "modified": 1754753585288,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/22/d28d55ebfb3e13bd54ecef84eff22594fa4e34"
                }
              ]
            },
            {
              "name": "28",
              "type": "folder",
              "children": [
                {
                  "name": "cfea3da39077ea37771c1021b0b1fca7264bda",
                  "type": "file",
                  "size": 60,
                  "modified": 1754749178061,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/28/cfea3da39077ea37771c1021b0b1fca7264bda"
                }
              ]
            },
            {
              "name": "2a",
              "type": "folder",
              "children": [
                {
                  "name": "b67e8ca028c3d23b91343f4f78659170ffd7f7",
                  "type": "file",
                  "size": 158,
                  "modified": 1754750889971,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/2a/b67e8ca028c3d23b91343f4f78659170ffd7f7"
                }
              ]
            },
            {
              "name": "35",
              "type": "folder",
              "children": [
                {
                  "name": "5856856242204dc2656564406374589a4995da",
                  "type": "file",
                  "size": 105,
                  "modified": 1754751094346,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/35/5856856242204dc2656564406374589a4995da"
                }
              ]
            },
            {
              "name": "3b",
              "type": "folder",
              "children": [
                {
                  "name": "cfd42cdfa82031c006c775f9f0a04167baf22a",
                  "type": "file",
                  "size": 60,
                  "modified": 1754751094346,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/3b/cfd42cdfa82031c006c775f9f0a04167baf22a"
                }
              ]
            },
            {
              "name": "3c",
              "type": "folder",
              "children": [
                {
                  "name": "3898696b6c23571f7ffceff49047e32d4a9234",
                  "type": "file",
                  "size": 190,
                  "modified": 1754751094347,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/3c/3898696b6c23571f7ffceff49047e32d4a9234"
                }
              ]
            },
            {
              "name": "43",
              "type": "folder",
              "children": [
                {
                  "name": "734a04730ec497a5760cdf7c1cabc621396eac",
                  "type": "file",
                  "size": 304,
                  "modified": 1754749174994,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/43/734a04730ec497a5760cdf7c1cabc621396eac"
                }
              ]
            },
            {
              "name": "45",
              "type": "folder",
              "children": [
                {
                  "name": "026ae8930024a74109eae1a5260423720ae6a0",
                  "type": "file",
                  "size": 55,
                  "modified": 1754749178062,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/45/026ae8930024a74109eae1a5260423720ae6a0"
                }
              ]
            },
            {
              "name": "48",
              "type": "folder",
              "children": [
                {
                  "name": "5b330033bfceb31cde773e169dedd567a16d5b",
                  "type": "file",
                  "size": 300,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/48/5b330033bfceb31cde773e169dedd567a16d5b"
                }
              ]
            },
            {
              "name": "4b",
              "type": "folder",
              "children": [
                {
                  "name": "1b0501579b4a7cc3bd419282746cc8a1e3bd8e",
                  "type": "file",
                  "size": 86,
                  "modified": 1754749178061,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/4b/1b0501579b4a7cc3bd419282746cc8a1e3bd8e"
                }
              ]
            },
            {
              "name": "4e",
              "type": "folder",
              "children": [
                {
                  "name": "43f0132149ed7de7930a16ed406bdcf8fbe3dc",
                  "type": "file",
                  "size": 3576,
                  "modified": 1754750884813,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/4e/43f0132149ed7de7930a16ed406bdcf8fbe3dc"
                }
              ]
            },
            {
              "name": "53",
              "type": "folder",
              "children": [
                {
                  "name": "4cffbe30c1ab71162ff0eaf43e35120e3948a4",
                  "type": "file",
                  "size": 105,
                  "modified": 1754750889969,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/53/4cffbe30c1ab71162ff0eaf43e35120e3948a4"
                }
              ]
            },
            {
              "name": "58",
              "type": "folder",
              "children": [
                {
                  "name": "981909759660f6d2677bf18107388ff0639972",
                  "type": "file",
                  "size": 77,
                  "modified": 1754749174995,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/58/981909759660f6d2677bf18107388ff0639972"
                }
              ]
            },
            {
              "name": "62",
              "type": "folder",
              "children": [
                {
                  "name": "ac8461444d1b8cce739104be8ca79e8dd6f6e5",
                  "type": "file",
                  "size": 82,
                  "modified": 1754749178062,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/62/ac8461444d1b8cce739104be8ca79e8dd6f6e5"
                }
              ]
            },
            {
              "name": "69",
              "type": "folder",
              "children": [
                {
                  "name": "c6527a488ab59d4ba266dea1ad9d54df290a8b",
                  "type": "file",
                  "size": 141,
                  "modified": 1754751094346,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/69/c6527a488ab59d4ba266dea1ad9d54df290a8b"
                }
              ]
            },
            {
              "name": "71",
              "type": "folder",
              "children": [
                {
                  "name": "2c730943565f9031f0a932f09610945bdb9ca9",
                  "type": "file",
                  "size": 411,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/71/2c730943565f9031f0a932f09610945bdb9ca9"
                }
              ]
            },
            {
              "name": "74",
              "type": "folder",
              "children": [
                {
                  "name": "b68022823a8507bb8a6a5ec9c5f0f5f3a139c3",
                  "type": "file",
                  "size": 189,
                  "modified": 1754750889969,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/74/b68022823a8507bb8a6a5ec9c5f0f5f3a139c3"
                }
              ]
            },
            {
              "name": "75",
              "type": "folder",
              "children": [
                {
                  "name": "960da906af844351891ca45cf38c4961693639",
                  "type": "file",
                  "size": 388,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/75/960da906af844351891ca45cf38c4961693639"
                }
              ]
            },
            {
              "name": "78",
              "type": "folder",
              "children": [
                {
                  "name": "d5c6ee86c10523133f07bf05fccf10c7a751be",
                  "type": "file",
                  "size": 129,
                  "modified": 1754749178064,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/78/d5c6ee86c10523133f07bf05fccf10c7a751be"
                }
              ]
            },
            {
              "name": "7f",
              "type": "folder",
              "children": [
                {
                  "name": "87d66d6e8a45ff31530fd48c026def46e96a7f",
                  "type": "file",
                  "size": 82,
                  "modified": 1754750889969,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/7f/87d66d6e8a45ff31530fd48c026def46e96a7f"
                }
              ]
            },
            {
              "name": "81",
              "type": "folder",
              "children": [
                {
                  "name": "ae5349027d26be285e7ef789ff0ae2a606b577",
                  "type": "file",
                  "size": 106,
                  "modified": 1754749178061,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/81/ae5349027d26be285e7ef789ff0ae2a606b577"
                }
              ]
            },
            {
              "name": "8e",
              "type": "folder",
              "children": [
                {
                  "name": "cd0e4849c1f30043486df819d4f178dcff07e1",
                  "type": "file",
                  "size": 320,
                  "modified": 1754753588409,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/8e/cd0e4849c1f30043486df819d4f178dcff07e1"
                }
              ]
            },
            {
              "name": "93",
              "type": "folder",
              "children": [
                {
                  "name": "1a3b7fcdbab516dbbc3d0171eb7016b6b0e6d3",
                  "type": "file",
                  "size": 155,
                  "modified": 1754749174996,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/93/1a3b7fcdbab516dbbc3d0171eb7016b6b0e6d3"
                }
              ]
            },
            {
              "name": "96",
              "type": "folder",
              "children": [
                {
                  "name": "75c98f17e677b775ec9021477f1f425cb5fd68",
                  "type": "file",
                  "size": 121,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/96/75c98f17e677b775ec9021477f1f425cb5fd68"
                }
              ]
            },
            {
              "name": "97",
              "type": "folder",
              "children": [
                {
                  "name": "09c9397df2d4612eef1b0481a2c622f3bddd3d",
                  "type": "file",
                  "size": 361,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/97/09c9397df2d4612eef1b0481a2c622f3bddd3d"
                }
              ]
            },
            {
              "name": "98",
              "type": "folder",
              "children": [
                {
                  "name": "13bcfbbb145a51107a377c0c0f3f2405845c4b",
                  "type": "file",
                  "size": 104,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/98/13bcfbbb145a51107a377c0c0f3f2405845c4b"
                }
              ]
            },
            {
              "name": "a0",
              "type": "folder",
              "children": [
                {
                  "name": "9fe178800e5ad2e7b72e2007de95fe8cb82410",
                  "type": "file",
                  "size": 61,
                  "modified": 1754749178062,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/a0/9fe178800e5ad2e7b72e2007de95fe8cb82410"
                }
              ]
            },
            {
              "name": "a4",
              "type": "folder",
              "children": [
                {
                  "name": "2ac13fa220efc6c9f8f34144a120d838121695",
                  "type": "file",
                  "size": 221,
                  "modified": 1754751090734,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/a4/2ac13fa220efc6c9f8f34144a120d838121695"
                }
              ]
            },
            {
              "name": "a8",
              "type": "folder",
              "children": [
                {
                  "name": "725147bbe66332a9fe98c3f26221e8cd9912a5",
                  "type": "file",
                  "size": 160,
                  "modified": 1754749174995,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/a8/725147bbe66332a9fe98c3f26221e8cd9912a5"
                },
                {
                  "name": "a6bda78407be3d05d290ea015c1b51d27188c0",
                  "type": "file",
                  "size": 24,
                  "modified": 1754749174994,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/a8/a6bda78407be3d05d290ea015c1b51d27188c0"
                }
              ]
            },
            {
              "name": "ac",
              "type": "folder",
              "children": [
                {
                  "name": "a6b0312514d6bbf7050ea02e20c7f6087f7209",
                  "type": "file",
                  "size": 159,
                  "modified": 1754751094349,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/ac/a6b0312514d6bbf7050ea02e20c7f6087f7209"
                }
              ]
            },
            {
              "name": "c2",
              "type": "folder",
              "children": [
                {
                  "name": "aeb1a28fee85c6057b2db651531fa1cb2249e5",
                  "type": "file",
                  "size": 107,
                  "modified": 1754749174994,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/c2/aeb1a28fee85c6057b2db651531fa1cb2249e5"
                }
              ]
            },
            {
              "name": "ce",
              "type": "folder",
              "children": [
                {
                  "name": "39a9497d17fad0659ed6a2b2263a6b1787630a",
                  "type": "file",
                  "size": 83,
                  "modified": 1754751094346,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/ce/39a9497d17fad0659ed6a2b2263a6b1787630a"
                }
              ]
            },
            {
              "name": "cf",
              "type": "folder",
              "children": [
                {
                  "name": "8466e5b82c7e04cc2af0415aec3931f195f2eb",
                  "type": "file",
                  "size": 243,
                  "modified": 1754749174996,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/cf/8466e5b82c7e04cc2af0415aec3931f195f2eb"
                }
              ]
            },
            {
              "name": "d0",
              "type": "folder",
              "children": [
                {
                  "name": "2a25bb9eae103a1ae7da51936ee495579ba335",
                  "type": "file",
                  "size": 66,
                  "modified": 1754749178061,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/d0/2a25bb9eae103a1ae7da51936ee495579ba335"
                }
              ]
            },
            {
              "name": "d2",
              "type": "folder",
              "children": [
                {
                  "name": "ee8f3f75daebc039fb4e3f7154f83f0f783c90",
                  "type": "file",
                  "size": 3394,
                  "modified": 1754753585289,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/d2/ee8f3f75daebc039fb4e3f7154f83f0f783c90"
                }
              ]
            },
            {
              "name": "d5",
              "type": "folder",
              "children": [
                {
                  "name": "40af72fed2bca2ca63913e3819400b2101bd29",
                  "type": "file",
                  "size": 189,
                  "modified": 1754749178062,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/d5/40af72fed2bca2ca63913e3819400b2101bd29"
                }
              ]
            },
            {
              "name": "ec",
              "type": "folder",
              "children": [
                {
                  "name": "e54767ba43f364b1cb1a7b219dd17b86e5ba07",
                  "type": "file",
                  "size": 158,
                  "modified": 1754753588410,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/objects/ec/e54767ba43f364b1cb1a7b219dd17b86e5ba07"
                }
              ]
            },
            {
              "name": "info",
              "type": "folder",
              "children": [
              ]
            },
            {
              "name": "pack",
              "type": "folder",
              "children": [
              ]
            }
          ]
        },
        {
          "name": "refs",
          "type": "folder",
          "children": [
            {
              "name": "heads",
              "type": "folder",
              "children": [
                {
                  "name": "main",
                  "type": "file",
                  "size": 41,
                  "modified": 1754753588410,
                  "url": "https://fascinating-babka-9cd698.netlify.app/.git/refs/heads/main"
                }
              ]
            },
            {
              "name": "remotes",
              "type": "folder",
              "children": [
                {
                  "name": "origin",
                  "type": "folder",
                  "children": [
                    {
                      "name": "HEAD",
                      "type": "file",
                      "size": 30,
                      "modified": 1754749216548,
                      "url": "https://fascinating-babka-9cd698.netlify.app/.git/refs/remotes/origin/HEAD"
                    },
                    {
                      "name": "main",
                      "type": "file",
                      "size": 41,
                      "modified": 1754753594163,
                      "url": "https://fascinating-babka-9cd698.netlify.app/.git/refs/remotes/origin/main"
                    }
                  ]
                }
              ]
            },
            {
              "name": "tags",
              "type": "folder",
              "children": [
              ]
            }
          ]
        },
        {
          "name": "COMMIT_EDITMSG",
          "type": "file",
          "size": 2,
          "modified": 1754753588410,
          "url": "https://fascinating-babka-9cd698.netlify.app/.git/COMMIT_EDITMSG"
        },
        {
          "name": "config",
          "type": "file",
          "size": 266,
          "modified": 1754749183885,
          "url": "https://fascinating-babka-9cd698.netlify.app/.git/config"
        },
        {
          "name": "description",
          "type": "file",
          "size": 73,
          "modified": 1754748752528,
          "url": "https://fascinating-babka-9cd698.netlify.app/.git/description"
        },
        {
          "name": "FETCH_HEAD",
          "type": "file",
          "size": 97,
          "modified": 1754753724054,
          "url": "https://fascinating-babka-9cd698.netlify.app/.git/FETCH_HEAD"
        },
        {
          "name": "HEAD",
          "type": "file",
          "size": 21,
          "modified": 1754748755542,
          "url": "https://fascinating-babka-9cd698.netlify.app/.git/HEAD"
        },
        {
          "name": "index",
          "type": "file",
          "size": 2011,
          "modified": 1754753588409,
          "url": "https://fascinating-babka-9cd698.netlify.app/.git/index"
        },
        {
          "name": "ORIG_HEAD",
          "type": "file",
          "size": 41,
          "modified": 1754753592321,
          "url": "https://fascinating-babka-9cd698.netlify.app/.git/ORIG_HEAD"
        }
      ]
    },
    {
      "name": "public",
      "type": "folder",
      "children": [
        {
          "name": "C++",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
                {
                  "name": "de_i18n.yaml",
                  "type": "file",
                  "size": 107,
                  "modified": 1754750855700,
                  "url": "https://fascinating-babka-9cd698.netlify.app/public/C%2B%2B/i18n/de_i18n.yaml"
                },
                {
                  "name": "jp_i18n.yaml",
                  "type": "file",
                  "size": 122,
                  "modified": 1754750855700,
                  "url": "https://fascinating-babka-9cd698.netlify.app/public/C%2B%2B/i18n/jp_i18n.yaml"
                }
              ]
            },
            {
              "name": "CPP_de.html",
              "type": "file",
              "size": 862,
              "modified": 1754750855911,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/C%2B%2B/CPP_de.html"
            },
            {
              "name": "CPP_en.html",
              "type": "file",
              "size": 844,
              "modified": 1754750855771,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/C%2B%2B/CPP_en.html"
            },
            {
              "name": "CPP_jp.html",
              "type": "file",
              "size": 892,
              "modified": 1754750855842,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/C%2B%2B/CPP_jp.html"
            }
          ]
        },
        {
          "name": "Linux",
          "type": "folder",
          "children": [
            {
              "name": "Linux_install_en.html",
              "type": "file",
              "size": 382,
              "modified": 1754750855700,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/Linux/Linux_install_en.html"
            }
          ]
        },
        {
          "name": "Netlify",
          "type": "folder",
          "children": [
            {
              "name": "Netlify_en.html",
              "type": "file",
              "size": 467,
              "modified": 1754750855940,
              "url": "https://fascinating-babka-9cd698.netlify.app/public/Netlify/Netlify_en.html"
            }
          ]
        }
      ]
    },
    {
      "name": "src",
      "type": "folder",
      "children": [
        {
          "name": "C++",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
                {
                  "name": "de_i18n.yaml",
                  "type": "file",
                  "size": 107,
                  "modified": 1754744695563,
                  "url": "https://fascinating-babka-9cd698.netlify.app/src/C%2B%2B/i18n/de_i18n.yaml"
                },
                {
                  "name": "jp_i18n.yaml",
                  "type": "file",
                  "size": 122,
                  "modified": 1754744705563,
                  "url": "https://fascinating-babka-9cd698.netlify.app/src/C%2B%2B/i18n/jp_i18n.yaml"
                }
              ]
            },
            {
              "name": "CPP.md",
              "type": "file",
              "size": 249,
              "modified": 1754744781382,
              "url": "https://fascinating-babka-9cd698.netlify.app/src/C%2B%2B/CPP.md"
            }
          ]
        },
        {
          "name": "Linux",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
              ]
            },
            {
              "name": "Linux_install.md",
              "type": "file",
              "size": 208,
              "modified": 1754748932087,
              "url": "https://fascinating-babka-9cd698.netlify.app/src/Linux/Linux_install.md"
            }
          ]
        },
        {
          "name": "Netlify",
          "type": "folder",
          "children": [
            {
              "name": "i18n",
              "type": "folder",
              "children": [
              ]
            },
            {
              "name": "Netlify.md",
              "type": "file",
              "size": 353,
              "modified": 1754748660946,
              "url": "https://fascinating-babka-9cd698.netlify.app/src/Netlify/Netlify.md"
            }
          ]
        }
      ]
    },
    {
      "name": ".gitignore",
      "type": "file",
      "size": 9,
      "modified": 1754748853512,
      "url": "https://fascinating-babka-9cd698.netlify.app/.gitignore"
    },
    {
      "name": "create_index",
      "type": "file",
      "size": 115136,
      "modified": 1754753787915,
      "url": "https://fascinating-babka-9cd698.netlify.app/create_index"
    },
    {
      "name": "create_index.cpp",
      "type": "file",
      "size": 6116,
      "modified": 1754753780344,
      "url": "https://fascinating-babka-9cd698.netlify.app/create_index.cpp"
    },
    {
      "name": "data.js",
      "type": "file",
      "size": 0,
      "modified": 1754753789632,
      "url": "https://fascinating-babka-9cd698.netlify.app/data.js"
    },
    {
      "name": "generator",
      "type": "file",
      "size": 632592,
      "modified": 1754750854374,
      "url": "https://fascinating-babka-9cd698.netlify.app/generator"
    },
    {
      "name": "generator.cpp",
      "type": "file",
      "size": 12192,
      "modified": 1754751085703,
      "url": "https://fascinating-babka-9cd698.netlify.app/generator.cpp"
    },
    {
      "name": "index.html",
      "type": "file",
      "size": 8327,
      "modified": 1754753364968,
      "url": "https://fascinating-babka-9cd698.netlify.app/index.html"
    },
    {
      "name": "prompt.chatgpt",
      "type": "file",
      "size": 362,
      "modified": 1754744397674,
      "url": "https://fascinating-babka-9cd698.netlify.app/prompt.chatgpt"
    }
  ]
};
